"https://stackoverflow.com/questions/1031396/how-to-share-one-vimrc-file-among-multiple-clients

let $url_rc = 'https://raw.githubusercontent.com/zhaohaoshu/rc/master/vim/vimrc'
let $url_rc_source = 'https://raw.githubusercontent.com/zhaohaoshu/rc/master/vim/vimrc_source'
let $local_path_rc_source = $MYVIMRC . '_source'

if has('win32')
    let $cmd_download_rc = '!powershell -command invoke-webrequest -uri ' . $url_rc . ' -header @{\"Cache-Control\"=\"max-age=0\"} -outfile ' . $MYVIMRC
    let $cmd_download_rc_source = '!powershell -command invoke-webrequest -uri ' . $url_rc_source . ' -header @{\"Cache-Control\"=\"max-age=0\"} -outfile ' . $local_path_rc_source
else
    let $cmd_download_rc = '!curl ' . $url_rc . ' -s -H "Cache-Control: max-age=0" -o ' . $MYVIMRC
    let $cmd_download_rc_source = '!curl ' . $url_rc_source . ' -s -H "Cache-Control: max-age=0" -o ' . $local_path_rc_source
endif

function! DownloadRc()
    silent! execute $cmd_download_rc
    silent! execute $cmd_download_rc_source
    redraw!
endfunction

command! DlRc call DownloadRc()

if !filereadable($local_path_rc_source)
    DlRc
endif

if filereadable($local_path_rc_source)
    source $local_path_rc_source
endif

